-- MySQL Script generated by MySQL Workbench
-- Fri Mar  5 19:51:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wockyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wockyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wockyDB` DEFAULT CHARACTER SET utf8 ;
USE `wockyDB` ;

-- -----------------------------------------------------
-- Table `wockyDB`.`Basic Stock Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wockyDB`.`basicStockInfo` ;

CREATE TABLE IF NOT EXISTS `wockyDB`.`basicStockInfo` (
  `Stock Symbol` VARCHAR(6) NOT NULL,
  `Stock Name` VARCHAR(50) NULL,
  `Sector` VARCHAR(30) NULL,
  `52 Week Low` FLOAT NULL,
  `52 Week High` FLOAT NULL,
  PRIMARY KEY (`Stock Symbol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wockyDB`.`Trade Dates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wockyDB`.`tradeDates` ;

CREATE TABLE IF NOT EXISTS `wockyDB`.`tradeDates` (
  `Stock Symbol` VARCHAR(6) NOT NULL,
  `Date` DATETIME NOT NULL,
  `Open Price` FLOAT NULL,
  `High Price` FLOAT NULL,
  `Low Price` FLOAT NULL,
  `Close Price` FLOAT NULL,
  `Volume` INT NULL,
  PRIMARY KEY (`Stock Symbol`, `Date`),
  CONSTRAINT `fk_Trade Dates_basicStockInfo`
    FOREIGN KEY (`Stock Symbol`)
    REFERENCES `wockyDB`.`basicStockInfo` (`Stock Symbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Trade Dates_basicStockInfo_idx` ON `wockyDB`.`tradeDates` (`Stock Symbol` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `wockyDB`.`User Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wockyDB`.`userInfo` ;

CREATE TABLE IF NOT EXISTS `wockyDB`.`userInfo` (
  `Username` VARCHAR(15) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
